### ISSUE TITLE
What about latency? Can it be done in realtime?

### ISSUE THREAD

**Issue by DIYer22** [geopavlakos/hamer#1]
Thank you for your work. I couldn't find any information about the algorithm's running speed, so I would like to ask

**Comment by geopavlakos** [comment]
A single forward pass of the HaMeR network on a crop of a hand requires ~32ms on an RTX 3090. This doesn't include the hand detection part or the rendering of the demo.

**Comment by linjiangya** [comment]
> A single forward pass of the HaMeR network on a crop of a hand requires ~32ms on an RTX 3090. This doesn't include the hand detection part or the rendering of the demo.

What is the overall fps actually? I have been running this on a single Tesla T4, but it seems it takes around 3.8~4 seconds to process one image.

**Comment by ruoyiqiao** [comment]
> > A single forward pass of the HaMeR network on a crop of a hand requires ~32ms on an RTX 3090. This doesn't include the hand detection part or the rendering of the demo.
> 
> What is the overall fps actually? I have been running this on a single Tesla T4, but it seems it takes around 3.8~4 seconds to process one image.

Hi! Have you solved this problem, cuz I got like 0.5Hz generation speed on 3090. Thx in advance!
