### ISSUE TITLE
additional pip package requirements

### ISSUE THREAD

**Issue by Mine268** [geopavlakos/hamer#10]
after following the readme for package installation, additional packages are required according to the error report:

```
pyrootutils
webdataset
rich
hydra_colorlog
hydra-submitit-launcher
```

installing them with pip solves the problem.

**Comment by geopavlakos** [comment]
Did you run `pip install -e .[all]`, with `[all]` specified, as the readme recommends? If you did, and it was successful, you should get all these packages, which are listed [here](https://github.com/geopavlakos/hamer/blob/31c99eef9435989e18d2c8f785854ab9f55b271e/setup.py#L28). If you didn't specify `[all]`, that would explain why those packages in particular were not installed.

**Comment by Mine268** [comment]
> Did you run `pip install -e .[all]`, with `[all]` specified, as the readme recommends? If you did, and it was successful, you should get all these packages, which are listed [here](https://github.com/geopavlakos/hamer/blob/31c99eef9435989e18d2c8f785854ab9f55b271e/setup.py#L28). If you didn't specify `[all]`, that would explain why those packages in particular were not installed.

Great thanks for your reply, I tried using `pip install -e .[all]` but it somehow failed to run. This issue disappeared one day after.

But in all, I sincerely appreciate your suggestions.
