### ISSUE TITLE
unexpected keys

### ISSUE THREAD

**Issue by xiaoyudanaa** [geopavlakos/hamer#14]
![image](https://github.com/geopavlakos/hamer/assets/77732714/c4c51bd5-d655-42f9-b459-d5524c3fa4a0)
Dear author, when I run the demo.py, I encounter the problem in the image and would like to ask you if this is normal? How can I fix it?

**Comment by linjiangya** [comment]
same here

**Comment by geopavlakos** [comment]
This should not affect performance for the demo (this is a warning for the hand detection part, not for the hamer model), so you can safely ignore this warning.
