### ISSUE TITLE
multiple hand detected at one location

### ISSUE THREAD

**Issue by linjiangya** [geopavlakos/hamer#15]
Dear authors, thank you for your great work. I am now having two problems:

1. Where is the part that handedness (e.g. left, right) is used or applied to the MANO layer? I think the handedness is needed for generating the verts and the initialization of the MANO layer. But it seems that there is only one MANO layer in your code using MANO_RIGHT.pkl. (**Update:** Oh it seems to be here where you flipped the X axis: `verts[:,0] = (2*is_right-1)*verts[:,0]`... It makes sense now. )

2. Is there a maximum suppression operation? I have tested your code and it seems that sometimes there will be wrong detections like the below:

![image](https://github.com/geopavlakos/hamer/assets/38423714/c7696eb8-b0c1-4ee1-af3c-6360f3de431b)
![image](https://github.com/geopavlakos/hamer/assets/38423714/9e1524ef-6fed-4c00-8653-a359cc52937a)
![image](https://github.com/geopavlakos/hamer/assets/38423714/adf515b8-0330-436c-b30b-a75129a32508)

**Comment by geopavlakos** [comment]
You are correct. For the demo code, we don't perform a non-max suppression on the hand level, that's why you occasionally see some of these double detections. If you do a more careful suppression, you should be able to get rid of those.

**Comment by maliksyria** [comment]
> You are correct. For the demo code, we don't perform a non-max suppression on the hand level, that's why you occasionally see some of these double detections. If you do a more careful suppression, you should be able to get rid of those.

Thanks for your comment
Could you tell me please how to implement this on the out results ?
