### ISSUE TITLE
dataset tar

### ISSUE THREAD

**Issue by xiaoyudanaa** [geopavlakos/hamer#16]
Dear Author, I have read your HMR 2.0 before and now this Hamer article and I am very excited by the results. I would like to create something based on your article, but I don't know much about dataset preprocessing, so I'd like to ask you about it: how should I make a new dataset in the form of the tar balls that you originally used in your code? Looking forward to your reply.

**Comment by walsvid** [comment]
Same question, I want to know how to package third-party data into webdataset with similar format as current data? And preprocessing details. Looking forward to your reply.

**Comment by noahcao** [comment]
Have the same question here. Thanks!

**Comment by AaronFengZY** [comment]
I find there exist scale factor， what is mean?

**Comment by geopavlakos** [comment]
This documentation from a fellow user could be helpful: https://github.com/m-usamasaleem/annotation_files/blob/main/README.md
