### ISSUE TITLE
The epoch does not increase when training

### ISSUE THREAD

**Issue by xiaoyudanaa** [geopavlakos/hamer#17]
Dear author, I'm a student of Yebin Liu at Tsinghua University, I have a problem: I have trained the hamer on 8*A800 GPU as the original configuration, but the epoch is still 0 until I get to 1,000,000 steps and after I run the demo, there is a mismatch in the visualisation results, what can I do to fix it? Meanwhile, could you share the pre-processing steps for tar? Looking forward to your reply. 
<img width="1166" alt="290401965-66449de3-7270-45d0-855f-5d1d6f4ffeee" src="https://github.com/geopavlakos/hamer/assets/77732714/1b39a8d6-09e1-4df9-940e-682cb44ded3b">

**Comment by xiaoyudanaa** [comment]
When the training ends automatically, I get the following weights file:: epoch=0-step=1000000.ckpt

**Comment by linjiangya** [comment]
Same problem here. I tried to load the saved `epoch=0-step=1000000.ckpt` but it's not working at all (just like yours).

**Comment by xiaoyudanaa** [comment]
> Same problem here. I tried to train on a single A100 and got a `epoch=0-step=1000000.ckpt` and a `hamer_last.ckpt` then load the `epoch=0-step=1000000.ckpt` but it's not working at all (always fluctuating). Moreover, the loss value seems not to converge in the log file and the epoch number is also 0.
> 
> Here are examples of using official checkpoints and checkpoints of mine:
> 
> ![image](https://private-user-images.githubusercontent.com/38423714/298233694-b4eb0497-8b7f-4faa-8e5f-5df839ff0d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjkzMTksIm5iZiI6MTcwNTcyOTAxOSwicGF0aCI6Ii8zODQyMzcxNC8yOTgyMzM2OTQtYjRlYjA0OTctOGI3Zi00ZmFhLThlNWYtNWRmODM5ZmYwZDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1MzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4Zjc2NzZhN2NhNTk0ZTVjNGE0MDMwNjY1NzBlYmVlODJmZGE5ZTdjY2JiYjhjMTRmNWY4NzhhNjM1N2U4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5MdNCgK9TguQlYxy9k5V8L11n5_jBUID63WhiCB44cs) (using `epoch=0-step=1000000.ckpt`) ![image](https://private-user-images.githubusercontent.com/38423714/298234240-3d6c6295-edab-43f6-aee4-b36a6af45d2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjkzMTksIm5iZiI6MTcwNTcyOTAxOSwicGF0aCI6Ii8zODQyMzcxNC8yOTgyMzQyNDAtM2Q2YzYyOTUtZWRhYi00M2Y2LWFlZTQtYjM2YTZhZjQ1ZDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1MzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YjcwMmYxZDhiMThlZTRiZGM3YzdlY2E3ZTU4ZWJiYTE3Y2I0NzUyMmFjNzE5ZDEyMTE0YTVjOTBhNDdkM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aZ6mdMOZsCG2t2fIyLy9Q4tEOrGXh8k-YPvS0I8PfVg) (using the officially released model `hamer.ckpt`)
> 
> Here's the tensorboard log: ![image](https://private-user-images.githubusercontent.com/38423714/298236396-93ee5e86-d48e-4814-8bf8-c1cae58d09fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjkzMTksIm5iZiI6MTcwNTcyOTAxOSwicGF0aCI6Ii8zODQyMzcxNC8yOTgyMzYzOTYtOTNlZTVlODYtZDQ4ZS00ODE0LThiZjgtYzFjYWU1OGQwOWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1MzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZGU2YzVlMjcxZjBjYjIzMDk3YjViYjJhYjUxYmZhOGE5ZDdjMzZmMjk5MWQxNDhhNjIwNzVhN2RkYWVjOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2s5OOnFGif1Yrs339zh1pR1klrV6nT64TzADBjPe2s)

Hi, can I have your contact details? Let's discuss this together, my WeChat is: Weafree

**Comment by linjiangya** [comment]
> > Same problem here. I tried to train on a single A100 and got a `epoch=0-step=1000000.ckpt` and a `hamer_last.ckpt` then load the `epoch=0-step=1000000.ckpt` but it's not working at all (always fluctuating). Moreover, the loss value seems not to converge in the log file and the epoch number is also 0.
> > Here are examples of using official checkpoints and checkpoints of mine:
> > ![image](https://private-user-images.githubusercontent.com/38423714/298233694-b4eb0497-8b7f-4faa-8e5f-5df839ff0d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjkzMTksIm5iZiI6MTcwNTcyOTAxOSwicGF0aCI6Ii8zODQyMzcxNC8yOTgyMzM2OTQtYjRlYjA0OTctOGI3Zi00ZmFhLThlNWYtNWRmODM5ZmYwZDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1MzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4Zjc2NzZhN2NhNTk0ZTVjNGE0MDMwNjY1NzBlYmVlODJmZGE5ZTdjY2JiYjhjMTRmNWY4NzhhNjM1N2U4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5MdNCgK9TguQlYxy9k5V8L11n5_jBUID63WhiCB44cs) (using `epoch=0-step=1000000.ckpt`) ![image](https://private-user-images.githubusercontent.com/38423714/298234240-3d6c6295-edab-43f6-aee4-b36a6af45d2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjkzMTksIm5iZiI6MTcwNTcyOTAxOSwicGF0aCI6Ii8zODQyMzcxNC8yOTgyMzQyNDAtM2Q2YzYyOTUtZWRhYi00M2Y2LWFlZTQtYjM2YTZhZjQ1ZDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1MzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YjcwMmYxZDhiMThlZTRiZGM3YzdlY2E3ZTU4ZWJiYTE3Y2I0NzUyMmFjNzE5ZDEyMTE0YTVjOTBhNDdkM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aZ6mdMOZsCG2t2fIyLy9Q4tEOrGXh8k-YPvS0I8PfVg) (using the officially released model `hamer.ckpt`)
> > Here's the tensorboard log: ![image](https://private-user-images.githubusercontent.com/38423714/298236396-93ee5e86-d48e-4814-8bf8-c1cae58d09fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjkzMTksIm5iZiI6MTcwNTcyOTAxOSwicGF0aCI6Ii8zODQyMzcxNC8yOTgyMzYzOTYtOTNlZTVlODYtZDQ4ZS00ODE0LThiZjgtYzFjYWU1OGQwOWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1MzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZGU2YzVlMjcxZjBjYjIzMDk3YjViYjJhYjUxYmZhOGE5ZDdjMzZmMjk5MWQxNDhhNjIwNzVhN2RkYWVjOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2s5OOnFGif1Yrs339zh1pR1klrV6nT64TzADBjPe2s)
> 
> Hi, can I have your contact details? Let's discuss this together, my WeChat is: Weafree

Sure I have added.

**Comment by geopavlakos** [comment]
Replied at issue #24. Could you pull the latest changes and try again?
