### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'hamer_training_data/freihand_mocap.npz'

### ISSUE THREAD

**Issue by donghaoye** [geopavlakos/hamer#2]

**Comment by geopavlakos** [comment]
This file was indeed missing. We have updated the `hamer_training_data_part1.tar.gz` file, so please redownload it (run [this command](https://github.com/geopavlakos/hamer/blob/9552bce477650bcac3e88b89381be26599c58b84/fetch_training_data.sh#L2) and then untar). No need to redownload the other tars.
