### ISSUE TITLE
How to project pred_keypoints_2d onto the original image?

### ISSUE THREAD

**Issue by linjiangya** [geopavlakos/hamer#20]
I think the projected 2D keypoints are in the cropped image coordinate system. How can we transform them to visualize in the original image?

**Comment by Xeanloo** [comment]
Hello, were you able to solve this issue? I'm currently having problem trying to do this. It seems like the detection results are scaled to a certain value? 

![grafik](https://github.com/geopavlakos/hamer/assets/92534202/e2401331-189f-4f61-9d46-cb230cf2fcb6)

**Comment by Xeanloo** [comment]
I'm having trouble with this as well. Did you manage to visualize them now?

![hand_0_box](https://github.com/geopavlakos/hamer/assets/92534202/8cf1a995-8063-49ca-bc8d-d3cb8615d3f7)

**Comment by geopavlakos** [comment]
Please take a look at this reply (second paragraph):
https://github.com/shubham-goel/4D-Humans/issues/55#issuecomment-1773383934

**Comment by linjiangya** [comment]
> Please take a look at this reply (second paragraph): [shubham-goel/4D-Humans#55 (comment)](https://github.com/shubham-goel/4D-Humans/issues/55#issuecomment-1773383934)

Thank you for your reply. I actually already managed to project it using the function below and I think it's the same to your solution:

```
def convert_crop_coords_to_orig_img(bbox, keypoints, crop_size):
    # import IPython; IPython.embed(); exit()
    cx, cy, h = bbox[:, 0], bbox[:, 1], bbox[:, 2]

    # unnormalize to crop coords
    # keypoints = 0.5 * crop_size * (keypoints + 1.0)

    # rescale to orig img crop
    keypoints *= h[..., None, None] / crop_size

    # transform into original image coords
    keypoints[:,:,0] = (cx - h/2)[..., None] + keypoints[:,:,0]
    keypoints[:,:,1] = (cy - h/2)[..., None] + keypoints[:,:,1]
    return keypoints
```

But I am just wondering if there is a way to directly project it to raw image with a cam_trans for original image. I have tried to project using the `pred_cam_t_full` to do so but failed in the end. It was the line 432 ~ line 435 below:
![image](https://github.com/geopavlakos/hamer/assets/38423714/1670aae7-a482-49ab-9ba6-b986292b0768)

**Comment by geopavlakos** [comment]
Can you try using the value of `scaled_focal_length` for the focal length argument in the `perspective_projection()` function?

**Comment by geopavlakos** [comment]
What are the dimensions of the original image for this example (if possible, could you also attach it)?

**Comment by linjiangya** [comment]
It's (720, 1280, 3)

Here's the example and the script I am using now:
[demo_2.txt](https://github.com/geopavlakos/hamer/files/14201036/demo_2.txt)

![000000](https://github.com/geopavlakos/hamer/assets/38423714/b8e9121d-0aed-435e-9084-d0d192fe854c)

**Comment by geopavlakos** [comment]
I couldn't get the exact same numbers as you are (I didn't run your script), but two changes that you will need to do when you call `perspective_projection`:
- negate the x coordinate for the 3D keypoints of the left hands before passing them to the projection function (so, instead of running the `pred_joints[:,0] = (2*is_right-1)*pred_joints[:,0]` afterwards as you do now, just do `pred_keypoints_3d[:,:,0] = (2*is_right-1)*pred_keypoints_3d[:,:,0]` before the projection).
- `perspective_projection` takes as input also the `camera_center`. Since you project on the original image, you can use this input argument. In your case, it would be `[1280/2, 720/2]`, or more generally `[W/2, H/2]`.

With these changes, you should be able to project the 3D joints to the original image.

**Comment by linjiangya** [comment]
> I couldn't get the exact same numbers as you are (I didn't run your script), but two changes that you will need to do when you call `perspective_projection`:
> 
> * negate the x coordinate for the 3D keypoints of the left hands before passing them to the projection function (so, instead of running the `pred_joints[:,0] = (2*is_right-1)*pred_joints[:,0]` afterwards as you do now, just do `pred_keypoints_3d[:,:,0] = (2*is_right-1)*pred_keypoints_3d[:,:,0]` before the projection).
> * `perspective_projection` takes as input also the `camera_center`. Since you project on the original image, you can use this input argument. In your case, it would be `[1280/2, 720/2]`, or more generally `[W/2, H/2]`.
> 
> With these changes, you should be able to project the 3D joints to the original image.

I am sorry, this image is not what I used to produce the numbers before. But anyway, after making the two changes you mentioned, now it works! Thank you for pointing out the usage of `camera_center!` :)
![image](https://github.com/geopavlakos/hamer/assets/38423714/d074295f-86c5-42d3-8d5b-1b7dfe38c849)

Also, thank you for mentioning the timing to negate the x coordinate counts. I found that if I want to use `perspective_projection()` to get 2D keypoints on the raw image, I could only follow the order you said to negate the pred_keypoints_3d before projection because it's not correct to flip the hand by negating the x value by (`pred_joints[:,0] = (2*is_right-1)*pred_joints[:,0]`) as it's already de-normalized from [-0.5, 0.5]. However, if I use my `convert_crop_coords_to_orig_img()`, I can just negate the x coordinate after the projection (and before feeding into `convert_crop_coords_to_orig_img()`) like below, because the 2D keypoints are normalized to [-0.5, 0.5] so :
```
for n in range(batch_size):
    pred_joints[:,0] = (2*is_right-1)*pred_joints[:,0]
    all_pred_2d.append(pred_joints)
.
.
.
all_pred_2d = model_cfg.MODEL.IMAGE_SIZE * (all_pred_2d + 0.5)
all_pred_2d = convert_crop_coords_to_orig_img(bbox=all_bboxes, keypoints=all_pred_2d, crop_size=model_cfg.MODEL.IMAGE_SIZE)

# visualization below
.
.
.
```

Thank you so much for this! :)

**Comment by Solo4working** [comment]
> > I couldn't get the exact same numbers as you are (I didn't run your script), but two changes that you will need to do when you call `perspective_projection`:
> > 
> > * negate the x coordinate for the 3D keypoints of the left hands before passing them to the projection function (so, instead of running the `pred_joints[:,0] = (2*is_right-1)*pred_joints[:,0]` afterwards as you do now, just do `pred_keypoints_3d[:,:,0] = (2*is_right-1)*pred_keypoints_3d[:,:,0]` before the projection).
> > * `perspective_projection` takes as input also the `camera_center`. Since you project on the original image, you can use this input argument. In your case, it would be `[1280/2, 720/2]`, or more generally `[W/2, H/2]`.
> > 
> > With these changes, you should be able to project the 3D joints to the original image.
> 
> I am sorry, this image is not what I used to produce the numbers before. But anyway, after making the two changes you mentioned, now it works! Thank you for pointing out the usage of `camera_center!` :) ![image](https://private-user-images.githubusercontent.com/38423714/303201232-d074295f-86c5-42d3-8d5b-1b7dfe38c849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTM1OTAsIm5iZiI6MTczNDUxMzI5MCwicGF0aCI6Ii8zODQyMzcxNC8zMDMyMDEyMzItZDA3NDI5NWYtODZjNS00MmQzLThkNWItMWI3ZGZlMzhjODQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMGZkYTYzODQ1YTE4YWUwZDkyNjA2NWZiZWIzZDZkZmU5MmNiOTE3ODg0NzliMTIzMjliNzAzNzRlNzM1NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0rdv_ZNhN5HXkeSlyB6gFcWG0KB1OgsFMGiwh8AAd6o)
> 
> Also, thank you for mentioning the timing to negate the x coordinate counts. I found that if I want to use `perspective_projection()` to get 2D keypoints on the raw image, I could only follow the order you said to negate the pred_keypoints_3d before projection because it's not correct to flip the hand by negating the x value by (`pred_joints[:,0] = (2*is_right-1)*pred_joints[:,0]`) as it's already de-normalized from [-0.5, 0.5]. However, if I use my `convert_crop_coords_to_orig_img()`, I can just negate the x coordinate after the projection (and before feeding into `convert_crop_coords_to_orig_img()`) like below, because the 2D keypoints are normalized to [-0.5, 0.5] so :
> 
> ```
> for n in range(batch_size):
>     pred_joints[:,0] = (2*is_right-1)*pred_joints[:,0]
>     all_pred_2d.append(pred_joints)
> .
> .
> .
> all_pred_2d = model_cfg.MODEL.IMAGE_SIZE * (all_pred_2d + 0.5)
> all_pred_2d = convert_crop_coords_to_orig_img(bbox=all_bboxes, keypoints=all_pred_2d, crop_size=model_cfg.MODEL.IMAGE_SIZE)
> 
> # visualization below
> .
> .
> .
> ```
> 
> Thank you so much for this! :)

Hello, I have the same problem, could you share the code? this helps me a lot. 

: )

**Comment by AsteriaCao** [comment]
Hi, @Solo4working: 

I think @linjiangya discussed how to work with `convert_crop_coords_to_orig_img()` realized by himself/herself. As for transformation from `pred_keypoints_3d` to original image position, I have tried as @geopavlakos said in previous discussions, and the code may like this: 

![Image](https://github.com/user-attachments/assets/1e289b93-7f4c-46f0-a45c-5981eb8addb0)

Finally, just visualize `all_keypoints` in its original image and get results like this: 

![Image](https://github.com/user-attachments/assets/5c04c8fb-38bf-48cc-877f-83041fb591ce)

**Comment by Solo4working** [comment]
> Hi, [@Solo4working](https://github.com/Solo4working):
> 
> I think [@linjiangya](https://github.com/linjiangya) discussed how to work with `convert_crop_coords_to_orig_img()` realized by himself/herself. As for transformation from `pred_keypoints_3d` to original image position, I have tried as [@geopavlakos](https://github.com/geopavlakos) said in previous discussions, and the code may like this:
> 
> ![Image](https://github.com/user-attachments/assets/1e289b93-7f4c-46f0-a45c-5981eb8addb0)
> 
> Finally, just visualize `all_keypoints` in its original image and get results like this:
> 
> ![Image](https://github.com/user-attachments/assets/5c04c8fb-38bf-48cc-877f-83041fb591ce)

Thanks! I got it! 😀
