### ISSUE TITLE
Training loss does not converge

### ISSUE THREAD

**Issue by linjiangya** [geopavlakos/hamer#24]
_Originally posted by @linjiangya in https://github.com/geopavlakos/hamer/issues/17#issuecomment-1901318513_
            

Here are examples of using official checkpoints and checkpoints of mine:

![image](https://github.com/geopavlakos/hamer/assets/38423714/b4eb0497-8b7f-4faa-8e5f-5df839ff0d29) (using `epoch=0-step=1000000.ckpt`)
![image](https://github.com/geopavlakos/hamer/assets/38423714/3d6c6295-edab-43f6-aee4-b36a6af45d2a) (using the officially released model `hamer.ckpt`)

Here's the tensorboard log:
![image](https://github.com/geopavlakos/hamer/assets/38423714/93ee5e86-d48e-4814-8bf8-c1cae58d09fd)

**Comment by geopavlakos** [comment]
Thanks for pointing this out. I'm still investigating this, but I believe it happened due to the incorrect initialization of the backbone. I have fixed this, and the training losses are decreasing as expected. Could you pull the latest updates and give it another shot?

**Comment by xungeer29** [comment]
> Thanks for pointing this out. I'm still investigating this, but I believe it happened due to the incorrect initialization of the backbone. I have fixed this, and the training losses are decreasing as expected. Could you pull the latest updates and give it another shot?

I want to train hamer with vitpose_base as the backbone, but how to get the vitpose_backbone_base.pth?
