### ISSUE TITLE
Question Regarding Implementation of MPJPE and AUC Metrics

### ISSUE THREAD

**Issue by YuehengLuo** [geopavlakos/hamer#25]
Hi,
I was going through the code from your paper and was curious about the MPJPE and AUC metrics you mentioned. Are these included in the code you provided? Could you point me to where in your code these metrics are calculated, or offer any advice on how they could be integrated? I would be very grateful.

**Comment by geopavlakos** [comment]
We used the official implementation from [FreiHAND](https://github.com/lmb-freiburg/freihand) and [HO3D](https://github.com/shreyashampali/ho3d/blob/master/eval.py) for the calculations of these metrics.

**Comment by YuehengLuo** [comment]
Thanks!
