### ISSUE TITLE
downloading models

### ISSUE THREAD

**Issue by WangYuXuan2022** [geopavlakos/hamer#3]
Excuse me, I find out that the link (https://www.dropbox.com/s/6zejmxu0aur3568/hamer_demo_data.tar.gz) to retrieve the models now is closing, how can I handle it, thank you!

**Comment by brentyi** [comment]
+1 the file is too popular!
```
Link temporarily disabled

This can happen when the link has been shared or downloaded too many times in a day.

Check back later and we’ll open access to more people.
```

**Comment by carlosedubarreto** [comment]
Yeah, I had that too
![image](https://github.com/geopavlakos/hamer/assets/4061130/d465acfc-ce1e-4b14-bfd7-312e4ec377d6)

**Comment by carlosedubarreto** [comment]
for you guys trying to download, there is the hugginbg face link, that could be used to download the model

try using this command
`git lfs clone https://huggingface.co/spaces/geopavlakos/HaMeR`

**Comment by geopavlakos** [comment]
Thanks for pointing this out! This should be only temporary, but we have moved the model to a location that should be always accessible. Please run again the `fetch_demo_data.sh` command.

**Comment by WangYuXuan2022** [comment]
Thanks a lot.
