### ISSUE TITLE
Extracting 3D hand pose wrt. camera

### ISSUE THREAD

**Issue by Dhruv2012** [geopavlakos/hamer#30]
Hi,

I'm facing an issue in extracting 3D coordinates of hand wrt. camera (in metric scale) in the code. I tried a few things including `out['pred_keypoints_3d']`, `out['pred_vertices']`, and other variables in the model's output dictionary. However, the resulting 3D coordinates seem to be inaccurate. Would you mind pointing me to the correct way of doing this? 

Thanks in advance!

**Comment by geopavlakos** [comment]
You can get the 3D coordinates of the hand keypoints or hand vertices in the camera frame by adding `pred_cam_t_full` to the `out['pred_keypoints_3d']` or `out['pred_vertices']` respectively. If you check the demo code, `pred_cam_t_full` is computed using an arbitrary focal length value. If you have access to the camera intrinsics, you can use those to get a better estimate of the hand location.

**Comment by fnuabhimanyu8713** [comment]
@geopavlakos also you have to multiply the x-coordinate of the left hand by -1?
