### ISSUE TITLE
How to train HAMER with slurm?

### ISSUE THREAD

**Issue by shenwenhao01** [geopavlakos/hamer#31]
I am training HAMER on a cluster using the following command:

`srun -p ${PARTITION} \
    -f pt \
    --workspace-id ${WORK_SPACE} \
    --resource ${RESOURCE} \
    --job-name ${JOB_NAME} \
    --container-image ${CONTAINER_IMAGE} \
    sudo -E -u shenwenhao bash -c " 
    cd /mnt/AFS_shenwenhao/hamer &&
    /mnt/AFS_shenwenhao/.conda/envs/py10/bin/python train.py \
        exp_name=hamer_finetune_arctic \
        data=mix_all \
        experiment=hamer_vit_transformer \
        launcher=local"`

But I found that the model checkpoint is not saved and the tesnorboard log is also null. 

I notice that there are some config files related to training with slurm, but I really got into some trouble when I train HAMER with slurm. Could you please add some documents to show how to train HAMER with slurm?

**Comment by geopavlakos** [comment]
Regarding slurm, one way to launch is by doing minor modifications to the command we provide, i.e.,
`python train.py -m hydra/launcher=submitit_slurm exp_name=hamer data=mix_all experiment=hamer_vit_transformer trainer=gpu launcher=slurm`

Regarding the trainer strategy for multi-gpu training, this is also what we used, so it shouldn't influence training in a negative way.
