### ISSUE TITLE
Training details of the released model

### ISSUE THREAD

**Issue by ap229997** [geopavlakos/hamer#32]
The paper contains 2 variants of the model - trained with HINT and without HInt. Which version does the released model correspond to? Also, is there a timeline for the release of HInt dataset?

**Comment by geopavlakos** [comment]
The released model has not been trained on HInt.

**Comment by GloryyrolG** [comment]
hi @geopavlakos @Kaszanas @ntvthuyen et al.

i tried to finetune the released ckpt but found performance on hint drops while performance on other eval datasets does not, which looks like a distribution shift. did u have any idea about the phenomenon? thx & rgds,
