### ISSUE TITLE
Will HInt dataset release?

### ISSUE THREAD

**Issue by yao5401** [geopavlakos/hamer#33]
Thanks for your work. I found dataset pics in paper are welI labeled. Are they data in HInt？
I download all dataset in fetch_training_data.sh, but I did not find the HInt. Will this dataset release?

**Comment by geopavlakos** [comment]
Indeed, the examples with 2D keypoint labels that you see in the paper are from HInt. We have released the HInt dataset [here](https://github.com/ddshan/hint).
