### ISSUE TITLE
Regarding the issues that occurred during training

### ISSUE THREAD

**Issue by tobottyx** [geopavlakos/hamer#35]
Hello, I followed the instructions in the "readme.md" to train the model and I would like to ask about the hardware environment you used during training, including memory and graphics card specifications. I suspect there might be a memory leak issue during my training process, as the memory usage keeps increasing, preventing the training from completing. Thank you.

**Comment by tinatiansjz** [comment]
Same question. I am also facing the memory leak problem right now.

**Comment by tobottyx** [comment]
I changed the number of processes read from the data (Num_workers) to match your gpu training speed
