### ISSUE TITLE
About the relative coordinates of 3D hand key points

### ISSUE THREAD

**Issue by Derek0907** [geopavlakos/hamer#36]
Hi,
It's a wonderful job! I've got a question, when dealing with my study, I only focus on the pose itself (Don't focus on the location in the picture/ frame view), which is reflected in metric PA-MPJPE.
I'm confused with the reference of the predicted 3D hand key points directly running after the demo.py, because I didn't find a point where the coordinate is zero. Do I need to transfer these coordinates to the same reference( eg. set the root point coordinate to zero) when calculating the loss between the ground truth (predicted 3D hand points coordinates) and the predicted hand coordinates?

Thanks in advance!

**Comment by fnuabhimanyu8713** [comment]
This may help you https://github.com/geopavlakos/hamer/issues/30#issuecomment-1961760722

**Comment by geopavlakos** [comment]
If you evaluate with PA-MPJPE, then the Procrustes Alignment will automatically translate, rotate and scale the prediction to optimally match your GT, so you don't need to do any updates to the predicted 3D hand coordinates.

**Comment by Derek0907** [comment]
> This may help you [#30 (comment)](https://github.com/geopavlakos/hamer/issues/30#issuecomment-1961760722)

Thanks a lot!

**Comment by Derek0907** [comment]
> If you evaluate with PA-MPJPE, then the Procrustes Alignment will automatically translate, rotate and scale the prediction to optimally match your GT, so you don't need to do any updates to the predicted 3D hand coordinates.

Thank you!
