### ISSUE TITLE
Present Checkpoint does not match Metrics reported in Table-1 in Paper: arXiv:2312.05251

### ISSUE THREAD

**Issue by aviralchharia** [geopavlakos/hamer#37]
Hi, I used the standard FreiHAND .pred and .eval code for testing the released model weights, but seems that the released variant is a previous checkpoint of the SOTA (or perhaps I may be using the .eval incorrectly?). Can the authors suggest if any correction is needed in the original [FreiHAND .eval code](https://github.com/lmb-freiburg/freihand/blob/master/eval.py) to match the metrics reported in the paper? I directly loaded the HaMeR model to the [FreiHAND .pred file](https://github.com/lmb-freiburg/freihand/blob/master/pred.py), (following the Demo code released by the authors), to make predictions and then ran .eval.

<img src="https://github.com/geopavlakos/hamer/assets/62457915/b2553d34-ad39-45bf-a7c4-0a21924d6f65" width="300">

**Comment by geopavlakos** [comment]
The evaluation code and the checkpoint should be the same. Is it possible that you don't provide the images correctly to the network (e.g., the scale is wrong)? Could you visualize the image that you give as input to the HaMeR network?
