### ISSUE TITLE
Evaluation model for HO3D

### ISSUE THREAD

**Issue by dqj5182** [geopavlakos/hamer#39]
I wish to test the model on HO3D dataset as presented at the paper's Table 2. Is the model evaluated at Table 2 same as the demo model that can be downloaded at "fetch_demo_data.sh" with the script "gdown https://drive.google.com/uc?id=1mv7CUAnm73oKsEEG1xE3xH2C_oqcFSzT"?

If not, may I get the pre-trained weight of the model evaluated at Table 2?

**Comment by geopavlakos** [comment]
Yes, the checkpoint is the same as the one you download with the demo data.

**Comment by dqj5182** [comment]
I see! Thanks for your response!
