### ISSUE TITLE
The visual results from validation_step are wrong.

### ISSUE THREAD

**Issue by donghaoye** [geopavlakos/hamer#4]
Maybe the checkpoint is not updated correctly?

<img width="1166" alt="image" src="https://github.com/geopavlakos/hamer/assets/5196528/66449de3-7270-45d0-855f-5d1d6f4ffeee">

**Comment by donghaoye** [comment]
Could you please provide me with the paper version of the hamer_vit_transformer.yaml file?

I am not sure that the batch_size is 8?

**Comment by donghaoye** [comment]
The batchsize is the main reason because the loss is a sum loss.

**Comment by xiaoyudanaa** [comment]
Hello, I have a similar problem: I have trained the hamer on 8*A800 GPU as the original configuration, but the epoch is still 0 until I get to 1,000,000 steps and after I run the demo, there is a mismatch in the visualisation results, what can I do to fix it? Looking forward to your reply.

**Comment by xiaoyudanaa** [comment]
> The batchsize is the main reason because the loss is a sum loss.
Hello, I have a similar problem: I have trained the hamer on 8*A800 GPU as the original configuration, but the epoch is still 0 until I get to 1,000,000 steps and after I run the demo, there is a mismatch in the visualisation results, what can I do to fix it? Looking forward to your reply.
