### ISSUE TITLE
mano mean parameter

### ISSUE THREAD

**Issue by luoxue-star** [geopavlakos/hamer#41]
May I ask how the mano_mean_params.npz file was obtained? Is it done by calculating the average of all poses and shapes? If this file is not present, what should the `cfg.MODEL.MANO_HEAD.IEF_ITERS` in the MANO HEAD forward be set to? Looking forward to your reply soon. Thanks!

**Comment by geopavlakos** [comment]
For the pose parameters, we use the mean hand pose from MANO (`hands_mean`). For the shape parameters, we inherit the average shape used by [HMR networks](https://github.com/akanazawa/hmr) (which is indeed computed as average across all body shapes from MoCap data).

The pretrained network expects this file to be available. If you don't want to use this file and you train a new model, I expect you will still get good performance regardless (maybe with a small drop).
