### ISSUE TITLE
The provided training data seems to have some missing parts.

### ISSUE THREAD

**Issue by StevenZzz07** [geopavlakos/hamer#42]
Based on the google drive link you provided, I download all the training data, as follows: 
![image](https://github.com/geopavlakos/hamer/assets/56421441/a083f283-cf8c-45f7-879a-b7874cfd14b5)
![image](https://github.com/geopavlakos/hamer/assets/56421441/bf88836a-35ad-4d8e-9de2-dc42e27e4606)
However, the [training config](https://github.com/geopavlakos/hamer/blob/main/hamer/configs/datasets_tar.yaml) provided in the git repo includes training data more than above mentioned. The missing parts include COCOW-TRAIN, RHD-TRAIN, MPIINZSL-TRAIN, H2O3D-TRAIN and FREIHAND-MOCAP. So, I am questioning whether the provided google drive data link is incomplete, if there is something wrong with my operations.

**Comment by geopavlakos** [comment]
All the data is expected to be in the files downloaded from google drive.
Are you sure you downloaded/extracted all the data correctly? It looks like you have downloaded almost ~200Gb for the .tar.gz files, but the individual datasets after extraction are below 100Gb.

**Comment by StevenZzz07** [comment]
> All the data is expected to be in the files downloaded from google drive. Are you sure you downloaded/extracted all the data correctly? It looks like you have downloaded almost ~200Gb for the .tar.gz files, but the individual datasets after extraction are below 100Gb.
Sorry for my mistakes. The issue mentioned above was caused by incomplete file I downloaded. The problem is resolved after I re-downloaded it. Thank you for your response.
