### ISSUE TITLE
OSError: [Errno 38] Function not implemented: '../../tools'

### ISSUE THREAD

**Issue by ireneMsm2020** [geopavlakos/hamer#45]
when "pip install -v -e third-party/ViTPose"，I meet this error:
```
warning: no files found matching 'mmpose/.mim/model-index.yml'
  warning: no files found matching '*.py' under directory 'mmpose/.mim/configs'
  warning: no files found matching '*.yml' under directory 'mmpose/.mim/configs'
  warning: no files found matching '*.py' under directory 'mmpose/.mim/tools'
  warning: no files found matching '*.sh' under directory 'mmpose/.mim/tools'
  warning: no files found matching '*.py' under directory 'mmpose/.mim/demo'
 
```
os.symlink(src_relpath, tar_path)
    OSError: [Errno 38] Function not implemented: '../../tools' -> **

does anyone also meet this error?

**Comment by geopavlakos** [comment]
Is it possible that you cloned without `--recursive` and the ViTPose folder is empty? If so, you can run `git submodule update --init --recursive` and then try running the `pip install` command again.

**Comment by ireneMsm2020** [comment]
@geopavlakos  thanks for your replay, it is solved now
