### ISSUE TITLE
pose parameter confusion

### ISSUE THREAD

**Issue by twinkling13** [geopavlakos/hamer#46]
Really wonderful work! Please forgive me -- I am just starting to learn about MANO and mesh fitting. 

There seem to be 21 output keypoints, but there are only 15 + 1 rotation matrices (?) from the pose and the global orient. Am I understanding that correctly? What are the last rotation matrices? And is it possible to convert the rotation matrices to wxyz quaternions?

Thanks so much!

**Comment by geopavlakos** [comment]
The last few keypoints are not directly associated with a rotation. Instead, they are vertices from the estimated mesh (fingertips).

For this project, we only use rotation matrices and the axis-angle representation, but you could convert to other 3D rotation representations.

**Comment by twinkling13** [comment]
I see, thank you!

**Comment by twinkling13** [comment]
I see, thank you!
