### ISSUE TITLE
mano mean params.npz

### ISSUE THREAD

**Issue by TheVirtuoso7** [geopavlakos/hamer#48]
When running the train file, the problem "No such file or directory, _DATA/data/mano_mean_params.npz" appeared. Could you please provide this file? Or how do I get this file? Sorry, I'm new to this.Any advice would be greatly appreciated. Thanks.
![{37689357-C997-4f22-BA7A-7C5B24142548}](https://github.com/geopavlakos/hamer/assets/148689579/c97b2615-46f4-4d97-9707-8cc1e811aab5)

**Comment by geopavlakos** [comment]
You will need to download the demo data to get this file. Please check the [installation instructions](https://github.com/geopavlakos/hamer?tab=readme-ov-file#installation).

**Comment by TheVirtuoso7** [comment]
Thank you very much for your help.

**Comment by TheVirtuoso7** [comment]
> 您需要下载演示数据才能获取此文件。请查看[安装说明](https://github.com/geopavlakos/hamer?tab=readme-ov-file#installation)。
Thank you very much for your help.
