### ISSUE TITLE
How to run the Demo with video?

### ISSUE THREAD

**Issue by CAN-Lee** [geopavlakos/hamer#50]
Hi @geopavlakos,

Thanks for your amazing works. I learn a lot from you.

I run successfully the Demo with images (.jpg) in example data. The results are so exicted. Then I want to try the demo with any videos (.mp4).

However, it seems that the Demo code only supports the file types like *.jpg, *.png in parser. So, is it possible to run the Demo with video? Or how to implement it?

Really appreciate it!

Can

**Comment by geopavlakos** [comment]
You could extract the frames from the video using [ffmpeg](https://stackoverflow.com/questions/10225403/how-can-i-extract-a-good-quality-jpeg-image-from-a-video-file-with-ffmpeg), and then run the demo on all the frames with the demo code.

**Comment by CAN-Lee** [comment]
Hi @geopavlakos ,

Thanks for your rely. It is a good idea. I will try later.

Appreciate it !

Can
