### ISSUE TITLE
About overlapping problem while run the demo.py

### ISSUE THREAD

**Issue by taeyunwoo** [geopavlakos/hamer#51]
Hello.
First of all, I really appreciate your works!
Thank you for opening your code.

The reason why I leave this issue is that,
how to resolve the overlapping problem to **one hand** during rendering the estimated hand meshes with [demo.py](https://github.com/geopavlakos/hamer/blob/main/demo.py).

<img width="1000" alt="capture" src="https://github.com/geopavlakos/hamer/assets/59469419/170484d8-1770-4540-aae4-b2b620f282f3">

As we can see in the upper image, the rendered right hand is overlapped by two estimated meshes. (red-dotted boxes in the third row)

Does this problem occur, since the detectron2 estimates these bounding boxes, which are fed into HAMER model?
If not, can I solve this problem?

Sincerely.
TY.

**Comment by geopavlakos** [comment]
In this. case, you could consider suppressing the duplicates. At inference time, you have two hands with their keypoints being in almost exactly the same 2D locations. This should be easy to detect and remove the duplicate detections.
