### ISSUE TITLE
Could you tell me about the training environment?

### ISSUE THREAD

**Issue by MY-CODE-1981** [geopavlakos/hamer#53]
Under what kind of environment was the training of this program executed? For example, was it on Ubuntu, which company's GPU was used and what were its VRAM and clock speed? Did it utilize multiple GPUs? Given that EGL offscreen rendering is used, it is unlikely that a GPU server machine (a machine that typically operates without a display) was used. Currently, I have started training using an RTX 3090, but after two days, it has only progressed to epoch 4.

**Comment by geopavlakos** [comment]
The EGL rendering can be done on a headless machine, so that's not an issue for using a GPU server.
Check also this https://github.com/geopavlakos/hamer/issues/38#issuecomment-2096948172 for the training configuration.
