### ISSUE TITLE
About camera convertion

### ISSUE THREAD

**Issue by Jianxff** [geopavlakos/hamer#55]
Hi, the reconstruction result is quite well, but I got confused with the camera convertion for render.

I want to recover real-world metric position of the hand mesh, and I find the camera convertion on `cam_crop_to_full`. Could you tell me some detail about the following two lines of code? I wonder **What `bs` means** and **Why `tz` is calculated by multiplying `2`**. 

![image](https://github.com/user-attachments/assets/e536bc52-4386-498f-b313-52758820ba4b)

Thanks!

**Comment by geopavlakos** [comment]
Please check this issue for an explanation of how `tz` is calculated: https://github.com/shubham-goel/4D-Humans/issues/125#issuecomment-2142635931

**Comment by Jianxff** [comment]
Got it. Thanks.
