### ISSUE TITLE
demo.py gets unexpected results

### ISSUE THREAD

**Issue by PanchengZhao** [geopavlakos/hamer#56]
When I try to run demo.py, everything looks consistent with the sample provided in Colab, but I get abnormal results in demo_out. Do you know what is causing this please?

TERMIAL OUTPUT:
```
apex is not installed
apex is not installed
apex is not installed
/home/admin/miniconda3/lib/python3.10/site-packages/mmcv/cnn/bricks/transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/home/admin/miniconda3/lib/python3.10/site-packages/pytorch_lightning/utilities/migration/utils.py:49: PossibleUserWarning: The loaded checkpoint was produced with Lightning v2.0.3, which is newer than your current Lightning version: v1.9.4
  rank_zero_warn(
WARNING: You are using a MANO model, with only 10 shape coefficients.
load checkpoint from local path: .//_DATA/vitpose_ckpts/vitpose+_huge/wholebody.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: backbone.blocks.0.mlp.experts.0.weight, ........

/home/admin/miniconda3/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
downsampling_factor=1.1564687093098958
downsampling_factor=1.3775582313537598
downsampling_factor=0.7702547709147135
downsampling_factor=0.914677619934082
downsampling_factor=1.8311049143473308
downsampling_factor=1.2556150754292805
downsampling_factor=1.6385523478190105
downsampling_factor=2.174232006072998
downsampling_factor=4.0980275472005205
downsampling_factor=4.663273334503174
downsampling_factor=3.003650665283203
downsampling_factor=3.003650665283203
```

RESULTS:
![test1_all](https://github.com/user-attachments/assets/b68f4fe3-48f0-472b-a7a8-ae4c50570a53)
![test2_all](https://github.com/user-attachments/assets/1a8f189a-dc2e-4c51-b1b7-2edaa36a9e07)
![test3_all](https://github.com/user-attachments/assets/b3b2d63c-541e-4450-b606-93449644402e)

**Comment by geopavlakos** [comment]
Hmm, this is weird. Does the mesh output (obj files) look ok? I'm trying to figure out if it's an inference error, or a rendering error.

**Comment by PanchengZhao** [comment]
Thanks for the quick reply. I checked the mesh output, and it shows the same anomaly, which suggests that this is an inference error. I downloaded the data from [https://huggingface.co/hngan/hamer/tree/main](hngan/hamer). Could this be where the problem is originating?

**Comment by geopavlakos** [comment]
It would make sense to try downloading the data through the suggested links of this repo and try again.

**Comment by PanchengZhao** [comment]
I downloaded the data through the suggested links in this repo and tried again. Unfortunately, I get almost identical abnormal results. Could the problem be in the environment? I am further investigating this error, please keep me informed if you have any new insights! Thanks!

**Comment by PanchengZhao** [comment]
I reinstalled the environment and the problem was solved. The result looks nice. Thanks for your reply!

**Comment by Nicous20** [comment]
pip install numpy==1.24.4

I have faced the same questions and I use the older vision of numpy then solved.
