### ISSUE TITLE
How to deal with live videos?

### ISSUE THREAD

**Issue by Kafka157** [geopavlakos/hamer#58]
Hi @geopavlakos ,

I'm really interested in this outstanding work, and I have also learnt a lot from your corresponding essay!

I find the results of your demo is awesome, and the my own hand image can also be well-handled!

I am wondering whether 'HaHeR' is able to support the live video? For example, extracting real-time video frames. 

Looking forward to your reply!

Kafka

**Comment by geopavlakos** [comment]
Based on an earlier measurement (see here: https://github.com/geopavlakos/hamer/issues/1#issuecomment-1853232436), a single forward pass of HaMeR takes ~32ms. You will need to modify the demo code to operate on a live video, but it should be possible to run in real time.

**Comment by Kafka157** [comment]
I will soon try the live video. Appreciate it!

**Comment by Kafka157** [comment]
I have tried this model operate on live video,  however, it spent nearly 1.9 second on an video frame (A100). Perhaps it can not be well performed on real time..... Are there any suggestions?

**Comment by Kafka157** [comment]
I have tried this model operate on live video, however, it spent nearly 1.9 second on an video frame (RTX 3090). Perhaps it can not be well performed on real time..... Are there any suggestions?

**Comment by ruoyiqiao** [comment]
> I have tried this model operate on live video, however, it spent nearly 1.9 second on an video frame (RTX 3090). Perhaps it can not be well performed on real time..... Are there any suggestions?

Hi! Have you solved this problem, cuz I got the similar generation speed on 3090. If yes, Is there any inference optimatization technique is needed? Thx in advance!

**Comment by ntvthuyen** [comment]
Things you can do: 
- replace detectron2 detection model with smaller detection model
- replace vitpose++ with smaller pose estimation model 
- remove side_view rendering and turn off save mesh
