### ISSUE TITLE
How to get the 3D coordinates of the camera coordinate system of each vertices

### ISSUE THREAD

**Issue by hahamini** [geopavlakos/hamer#59]
I want to get the 3D coordinates of the camera coordinate system of each vertices.
In #30, it said to add pred_cam_t_full to vertices or keypoints, so I did that.
Then, for verification, I projected it to a 2D plane, but I think it's wrong, so I'm posting a question.

```python
...
pred_cam_t_full
vertices = out["pred_vertices"][0].detach().cpu().numpy()
cam_mat = np.array([[camera_matrix['fx'], 0, camera_matrix['cx']],
                    [0, camera_matrix['fy'], camera_matrix['cy']],
                    [0, 0, 1]])

def project_to_2d(vertices, K):
    vertices_2d = []
    for vertex in vertices:
        projected = K @ (vertex + pred_cam_t_full).T
        projected = projected / projected[-1]
        vertices_2d.append(projected[:2])
    return np.array(vertices_2d)

vertices_2d = project_to_2d(vertices, cam_mat)
```

**Comment by geopavlakos** [comment]
What values are you using for the camera matrix? The translation `pred_cam_t_full` is computed [here](https://github.com/geopavlakos/hamer/blob/dc19e5686198a7c3fc3938bff3951f238a85fd11/demo.py#L144) using specific intrinsics (focal length is the `scaled_focal_length` value and the center of projection is at the center of the image). You will need to use these values when you do the projection.

**Comment by hahamini** [comment]
> What values are you using for the camera matrix? The translation `pred_cam_t_full` is computed [here](https://github.com/geopavlakos/hamer/blob/dc19e5686198a7c3fc3938bff3951f238a85fd11/demo.py#L144) using specific intrinsics (focal length is the `scaled_focal_length` value and the center of projection is at the center of the image). You will need to use these values when you do the projection.

As you said, it is well projected on the cropped image frame.
Then how do you calculate the relationship between the cropped image and the original image?
I just want to get the 3D point of a specific vertex.
