### ISSUE TITLE
installing on windows

### ISSUE THREAD

**Issue by carlosedubarreto** [geopavlakos/hamer#6]
While testing on windows I've encontered 2 problems.

the first one was and EGL error.
I solved it commenting the lines that says 
`os.environ['PYOPENGL_PLATFORM'] = 'egl' `
![image](https://github.com/geopavlakos/hamer/assets/4061130/844897ce-87f3-4bff-b9cb-d9a478cb4483)

And another erro that I had was about the wrong path for the model, this error was causes by the function to update cachedir in hamer/model/__init__.py
I just changed to `update_cachedir=False`

![image](https://github.com/geopavlakos/hamer/assets/4061130/9c620474-5b06-4ada-a526-f2c6e8a3f71e)

and on the installation part its always a bit complicated to install detectron on windows. a way that helped me to install it was following the instruction on https://stackoverflow.com/questions/60631933/install-detectron2-on-windows-10/72784255#72784255

resuming, you need to follow these instructions (you can change the name of the venv created

```
conda create -n norfair python=3.9

conda install -c anaconda pywin32

conda install -c anaconda cython

pip install git+https://github.com/facebookresearch/fvcore

pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI

pip install av

conda install -c anaconda scipy

conda install -c anaconda ninja

pip install git+https://github.com/facebookresearch/detectron2.git
```

**Comment by carlosedubarreto** [comment]
I think that was all that I did. Good luck for you that will try to install on windows. It a bit more complicated, but not that much.

**Comment by carlosedubarreto** [comment]
@zwukong I had the same problem.
I ended up removing everything related to rendering to make it to work recently.
but I did ti a while ago, I actually dont remember where I did it, but I think iit was on the python file that we use to run the process

**Comment by zwukong** [comment]
Yes, i did the same way.render is useless to me. Thanks for your kind reply

**Comment by zwukong** [comment]
Thanks，trying,wrist is the most important， still not work yet. just want to make  hands animation easier 😄，maybe it is not necessary.
