### ISSUE TITLE
How to set the corret focal length with RealsenseD435i

### ISSUE THREAD

**Issue by GuoPingPan** [geopavlakos/hamer#62]
Hi Bro, thanks for making such a good job. But how can I get the right focal length for 3d keypoint reconstruction?
I had check #49 #30.  The crop image size is 256, and I use camera with resolution 640x480 which focal length is 324.
But using 324 as focal length  for `FOCAL_LENGTH` in model_config.yaml can't get the right depth corresponded to measurement.

The difference I mean is the output of the following code and the distance I measured directly from the wrist using a ruler perpendicular to the camera:
```
scaled_focal_length = model_cfg.EXTRA.FOCAL_LENGTH / model_cfg.MODEL.IMAGE_SIZE * img_size.max()
pred_cam_t_full = cam_crop_to_full(pred_cam, box_center, box_size, img_size, scaled_focal_length).detach().cpu().numpy()

global_orient = out["pred_mano_params"]["global_orient"][0][0].cpu().detach().numpy()
wrist_position = out["pred_keypoints_3d"][0][0].cpu().detach().numpy()
wrist_position = np.add(wrist_position, pred_cam_t_full[0])
print(wrist_position[0][-1])
```

**Comment by geopavlakos** [comment]
You will need to set `scaled_focal_length` to the value of the focal length of your camera, not `model_cfg.EXTRA.FOCAL_LENGTH`.

**Comment by GuoPingPan** [comment]
Sorry, I still can't get the correct distance. The measurement error is greater than 10cm.
Sould I change the `args.rescale_factor` of bellow?
```
dataset = ViTDetDataset(model_cfg, img, boxes, right, rescale_factor=args.rescale_factor)
dataloader = torch.utils.data.DataLoader(dataset, batch_size=8, shuffle=False, num_workers=0)

all_verts = []
all_cam_t = []
all_right = []

for batch in dataloader:
    batch = recursive_to(batch, device)
    with torch.no_grad():
        out = model(batch)

    multiplier = (2*batch['right']-1)
    pred_cam = out['pred_cam']
    pred_cam[:,1] = multiplier*pred_cam[:,1]
    box_center = batch["box_center"].float()
    box_size = batch["box_size"].float()
    img_size = batch["img_size"].float()
    multiplier = (2*batch['right']-1)
    scaled_focal_length = model_cfg.EXTRA.FOCAL_LENGTH / model_cfg.MODEL.IMAGE_SIZE * img_size.max()
    scaled_focal_length = 324
    print(img_size)
    pred_cam_t_full = cam_crop_to_full(pred_cam, box_center, box_size, img_size, scaled_focal_length).detach().cpu().numpy()

    global_orient = out["pred_mano_params"]["global_orient"][0][0].cpu().detach().numpy()
    wrist_position = out["pred_keypoints_3d"][0][0].cpu().detach().numpy()
    print(out["pred_keypoints_3d"].shape)
    wrist_position = np.add(wrist_position, pred_cam_t_full[0])
    print(wrist_position)
    input_patch = batch['img'][0].cpu() * (DEFAULT_STD[:,None,None]/255) + (DEFAULT_MEAN[:,None,None]/255)
    input_patch = input_patch.permute(1,2,0).numpy()
    # cv2.imshow("abc", color_image)
    print(input_patch.shape)
    cv2.imshow("abc", (input_patch*255).astype(np.uint8))
    cv2.waitKey(33)
    continue

```

**Comment by geopavlakos** [comment]
If the focal length value is correct, then the above code should provide an estimate for the wrist location. Please remember that this is an approximation and because of the scale ambiguity in monocular capture, the absolute depth estimate might be less accurate (please see also [this issue](https://github.com/geopavlakos/hamer/issues/60#issue-2459421979) that reports a ~4cm error in the absolute distance from the camera).

Out of curiosity, could you share the image you are using to test this and the ground truth/correct distance of the hand from the camera?

**Comment by GuoPingPan** [comment]
Thank you very much. After many tests, the error is indeed maintained within 5cm. Thank you again for your excellent work.
