### ISSUE TITLE
How to train with multi GPUs？

### ISSUE THREAD

**Issue by YHaooo-4508** [geopavlakos/hamer#64]
I got the error when train with multi GPUs.

> RuntimeError: It looks like your LightningModule has parameters that were not used in producing the loss returned by training_step. If this is intentional, you must enable the detection of unused parameters in DDP, either by setting the string value `strategy='ddp_find_unused_parameters_true'` or by setting the flag in the strategy with `strategy=DDPStrategy(find_unused_parameters=True)`.

Using `strategy: ddp_find_unused_parameters_true` can solve this error, but the training speed is very slow.

Could you please tell me how to solve this problem or how to train with muti GPUs?

**Comment by geopavlakos** [comment]
When running on multiple GPUs, we also use the strategy `ddp_find_unused_parameters_true` during training.

**Comment by qq456cvb** [comment]
We also experienced a similar issue, when using multi gpus with `ddp_find_unused_parameters_true`, the training speed is very slow, almost 1/6 of the speed on single gpu. Any ideas on how to train it faster with multi-gpus? Otherwise, it will take ~40 days for a full train.
