### ISSUE TITLE
About video consistency

### ISSUE THREAD

**Issue by haonanhe** [geopavlakos/hamer#65]
HaMer performs really well on estimation of a single image. However, when implemented on videos, inconsistency of mano poses and betas can be observed between frames. Is it possible to improve the consistency?

**Comment by geopavlakos** [comment]
HaMeR operates on each frame independently, so unfortunately the temporal consistency is not guaranteed. You could consider post-processing the HaMeR results, by optimizing them and encouraging the whole sequence to have the same shape parameters, and/or encourage neighboring frames to have similar poses.
