### ISSUE TITLE
Bug in inference or rendering

### ISSUE THREAD

**Issue by ntujy** [geopavlakos/hamer#68]
Thanks for the excellent work!

I am following the guide to run inference on videos. While some of them return accurate results, some frames seem not to have results. One example frame is as follows:
![1](https://github.com/user-attachments/assets/3a8fb077-0971-4dd2-a21d-4eac4e8ed848)

The output of the side view and all view are as follows:
![1_0](https://github.com/user-attachments/assets/d1b64901-7f72-40de-bb50-45f2d6b98212)
![1_all](https://github.com/user-attachments/assets/cad850d0-71eb-4850-b92e-097e7a8cd0c8)

I tried to print the pred_keypoints_3d from the output, the coordinates are as follows:
![Screenshot 2024-09-20 125739](https://github.com/user-attachments/assets/a6d6fb53-bde7-4204-b8ee-1f4e94b80de1)

So the model got some results but the rendering does not work.
Any possible reason that could lead to this? Look forward to your reply.

**Comment by geopavlakos** [comment]
This example looks ok on my end. How are you doing inference on video? Maybe you edited the code and introduced a bug? If you use the single frame demo on this image, it should work ok.
![369264064-3a8fb077-0971-4dd2-a21d-4eac4e8ed848_all](https://github.com/user-attachments/assets/5c9df6b8-bae8-4dbc-b127-cb4a47961c7d)

**Comment by ntujy** [comment]
The problem is solved by re-installing the virtual environment. Close the issue.
Thanks for your reply!
