### ISSUE TITLE
FreiHAND Competition Evaluation Server

### ISSUE THREAD

**Issue by m-usamasaleem** [geopavlakos/hamer#69]
Thank you for your outstanding work! I have been following it for some time now and truly appreciate your contributions.

I recently registered for the FreiHAND Competition but have not received any feedback yet. I’m curious about how participants are currently evaluating their results for the competition. The last submission on the leaderboard was on 08/31/22, so I wanted to check if the competition is still active or if there’s any way to obtain evaluation metrics for submissions.

![image](https://github.com/user-attachments/assets/657517a0-c463-4a1e-b128-6d14b81a8f3e)

**Comment by ava-121** [comment]
May I ask if your application has been approved? I’m running into the same problem and would really appreciate it if you could share your solution. Also, do you know of any other ways to solve the problem of getting the evaluation metrics?

**Comment by ramiroabigail5187-dot** [comment]
> May I ask if your application has been approved? I’m running into the same problem and would really appreciate it if you could share your solution. Also, do you know of any other ways to solve the problem of getting the evaluation metrics?
For evaluation on Freihand：https://github.com/lmb-freiburg/freihand and HO3D：https://github.com/anilesec/ho3d , you need to clone the corresponding GitHub repositories, follow the instructions in the README, copy the JSON files generated during training/evaluation to the corresponding folders, and then run the evaluation script to obtain the text file with evaluation metrics.
