### ISSUE TITLE
How to get pose with known extrinsic / intrinsic parameter

### ISSUE THREAD

**Issue by 1524101973** [geopavlakos/hamer#72]
Thank you for sharing the wonderful work.
May I ask you how can I modified the code if I have already got an extrinsic matrix for the camera?
Thank you

**Comment by geopavlakos** [comment]
[This line](https://github.com/geopavlakos/hamer/blob/dc19e5686198a7c3fc3938bff3951f238a85fd11/demo.py#L144) computes the translation of the hand in the camera frame, `pred_t_cam_full`. You need to give as input the focal length of your camera, for that translation to be estimated correctly.
Assuming you have placed the hand correctly in the camera frame, it is easy to transform the hand to your world frame using the camera extrinsics.
