### ISSUE TITLE
To map the MANO model to the SMPLX body using a mapping file, the following key information is required.

### ISSUE THREAD

**Issue by owowaaaz** [geopavlakos/hamer#74]
I'm currently using the mano.pkl file generated by HAMER to map it onto the SMPLX model, but I'm consistently encountering stretching issues in the model. Should I merge the mano.pkl file onto SMPLH, or do I need specific key parameters to replace the SMPLX hand model?

![mano_hand](https://github.com/user-attachments/assets/3777b6a6-6df1-4d57-8e51-d60281571667)

**Comment by geopavlakos** [comment]
Which parameters did you transfer to SMPLX from MANO? You probably only want to pass the `left/right_hand_pose` parameters.
Also, I'm not sure how you got the _mano.pkl_ file. This is not the output generated by our code.

**Comment by owowaaaz** [comment]
Thank you for your reply. The hand recognition in your project is extremely accurate, so I used the hand model generated by HAMER to pass the information of verts and faces to SMPL-X. I extracted all the keys from the ”out“ in the code,
 including 
”pred_keypoints_2d“, 
”pred_vertices“，
”pred_keypoints_3d“，
”focal_length“，
”pred_cam_t“，
”betas“，
”hand_pose“，
”global_orient“，and ”pred_cam”.  
Therefore, I thought mapping these keys could perfectly replace the hands in SMPL-X. However, the resulting model was not correct. Do you mean that I only need to pass the  “left/right_hand_pose”  parameters through the official SMPL-X mapping file 【MANO_SMPLX_vertex_ids.pkl】？

**Comment by geopavlakos** [comment]
You don't want to directly edit the vertices of SMPL-X, because the composition of the results will be incorrect like the result you got here. Instead, you will need to use the `hand_pose` output from HaMeR and map it to the `left_hand_pose` or `right_hand_pose` (depending on whether you have a right or a left hand) input of the SMPL-X model.
