### ISSUE TITLE
2d keypoints used in training

### ISSUE THREAD

**Issue by m-usamasaleem** [geopavlakos/hamer#79]
Thank you for your outstanding work! Could you kindly explain how you obtained the 2D keypoints for the training images in the OpenPose format? I specifically tried running OpenPose for 2D HandPose, but the keypoints I extracted don't match the level of detail reflected in your annotations.

While I do get some output, the accuracy isn't as good as yours. Could I be missing something in the process? In my case openpose seems very sensitive to bounding box of hands? How can I stabilize it?

I sincerely appreciate your time and guidance!

**Comment by geopavlakos** [comment]
All the images we used for training have ground truth annotations for 2D keypoints.

**Comment by m-usamasaleem** [comment]
Thankyou for your response. I really appreciate it.
