### ISSUE TITLE
3D Mesh to depth map

### ISSUE THREAD

**Issue by WangYuXuan2022** [geopavlakos/hamer#8]
Hi, I wonder how to convert the 3D mesh file(.obj) to depth map. Specially, how can I get the extrinsic and intrinsic matrix of the camera in this project, thank you!

**Comment by geopavlakos** [comment]
Every time we visualize the result, the depth map is also rendered (variable `rend_depth` [here](https://github.com/geopavlakos/hamer/blob/31c99eef9435989e18d2c8f785854ab9f55b271e/hamer/utils/renderer.py#L234)). You can edit the code to get access to this.
We don't estimate intrinsics. Instead, we render the result given a predefined focal length.
