### ISSUE TITLE
Possible to replace smplx wrist pose with hamer global orient?

### ISSUE THREAD

**Issue by ntujy** [geopavlakos/hamer#81]
I understand that HaMeR's hand poses could directly fit into SMPLX hand but can we also use "global orient" to replace wrist pose? 

I tested with several images but the results are weird. 

Below is my code **(for simplicity I only tested right hand)**:

```
def mix_pose(img_path, smplx_path, mano_path, meta_path):
    # read img, smplx and hamer results
    image = cv2.imread(img_path)
    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
    kwargs = dict(gender='neutral',
                    num_betas=10,
                    use_face_contour=True,
                    flat_hand_mean=True,
                    use_pca=False,
                    batch_size=1)  
    new_smplx = dict(np.load(smplx_path, allow_pickle=True))
    hamer_results = dict(np.load(mano_path, allow_pickle=True))
    r_root_pose = hamer_results['root_pose'][1, :]
    r_hand_pose = hamer_results['hand_pose'][1,:]

    # replace smplx right hand with hamer
    new_smplx['body_pose'][-1, :] = R.from_matrix(r_root_pose.squeeze()).as_rotvec()
    new_smplx['right_hand_pose'] = R.from_matrix(r_hand_pose.squeeze()).as_rotvec()
    intersect_key = list(set(new_smplx.keys()) & set(smplx_shape.keys()))
    body_model_param_tensor = {key: torch.tensor(
            np.array(new_smplx[key]).reshape(smplx_shape[key]), device=device, dtype=torch.float32)
                    for key in intersect_key if len(new_smplx[key]) > 0}
    meta = json.load(open(meta_path))
    smplx_model = smplx.create('../common/utils/human_model_files', 'smplx', **kwargs).to(device)
    focal_length = meta['focal']
    principal_point = meta['princpt']
    camera = pyrender.camera.IntrinsicsCamera(
            fx=focal_length[0], fy=focal_length[1],
            cx=principal_point[0], cy=principal_point[1],)
    
    # render pose
    rendered_image = render_pose(img=image,
                    body_model_param=body_model_param_tensor,
                    body_model=smplx_model,
                    camera=camera)
    
    # save rendered image and mix pose results
    cv2.imwrite('./render_img.jpg', rendered_image)
    res = {}
    for i in new_smplx:
        res[i] = new_smplx[i].reshape(1, -1)
    with open('./mix.pkl', 'wb') as f:
        pickle.dump(res, f)
```

The rendered images:
![image](https://github.com/user-attachments/assets/5d81155f-4ba7-4af7-9f2c-4dbbb51ae98e)

HaMeR rendered image is correct:
![image](https://github.com/user-attachments/assets/8fb59b39-3ea8-466e-b39c-517b9aadacf7)

Import the output pose to Blender SMPLX addon:
![image](https://github.com/user-attachments/assets/1f29814b-fe3d-4062-8d2d-b5928b40f3a7)

Would you mind sharing what might be the problem? Thank you!

**Comment by geopavlakos** [comment]
It’s not straightforward because HaMeR's global orientation represents the wrist’s rotation in the camera frame, while SMPLX’s hand orientation reflects the wrist’s rotation relative to the elbow. To align these, you’d likely need to propagate some updates to the arm pose, so it wouldn’t be as simple as just copying over HaMeR’s global orientation.

**Comment by fouralarmclock** [comment]
hello， did u solve the problem？ I met the same problem

**Comment by ntujy** [comment]
https://github.com/VincentHu19/Mano2Smpl-X
Can refer to this repo, basically you need to convert the global rotation of mano(wrist) from hamer results to local rotation of smplx

**Comment by ntujy** [comment]
> But the global rotation of mano is in camera frame right ?, how do i convert it into world frame?

Use extrinsics of the camera
