### ISSUE TITLE
Error Running on Windows

### ISSUE THREAD

**Issue by abcjoh** [geopavlakos/hamer#83]
Hi, 
Can you please guide how to resolve this error. While running the demo.py the code terminates with this error. Although all the packages relevant to EGL is installed in the venv still there is an error.

Please note I am setting up the hamer on the windows machine
**line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)**

**Comment by geopavlakos** [comment]
Unfortunately, we are not able to test the code on a windows device, but please check whether [this](https://github.com/geopavlakos/hamer/issues/6#issue-2042982089) could be helpful.
