### ISSUE TITLE
About the checkpoints of demo command

### ISSUE THREAD

**Issue by GlAYgroup** [geopavlakos/hamer#85]
Are the checkpoints of the model that can be retrieved in `bash fetch_demo_data.sh` trained using all of New days, VISOR, and Ego4D of the HInt dataset?

**Comment by geopavlakos** [comment]
The released model has not been trained on HInt.

**Comment by GlAYgroup** [comment]
Do you publish the models trained with HInt? Also, what are the demo models trained with?

**Comment by geopavlakos** [comment]
We only release the demo model that we reference in this repo. Please check [our config](https://github.com/geopavlakos/hamer/blob/df533a2d04b9e2ece7cf9d6cbc6982e140210517/hamer/configs_hydra/data/mix_all.yaml#L5) for the datasets used during training.

**Comment by GloryyrolG** [comment]
> The released model has not been trained on HInt.

hi @geopavlakos @Kaszanas @ntvthuyen et al.

i tried to finetune the released ckpt but found performance on hint drops while performance on other eval datasets does not, which looks like a distribution shift. did u have any idea about the phenomenon? thx & rgds,
