### ISSUE TITLE
left and right hand reconstruction is well separately, the combination is wrong

### ISSUE THREAD

**Issue by LuckyZxy182** [geopavlakos/hamer#87]
Thank for sharing your great work! 
I have a question!  The 3d reconstruction of left hand and right hand is very well separately， but the combination looks like wrong！I kown  that HaMeR processes only right hands in traning stage and infer left hand by fliping. And I use default focal_length. What is the reason? And how can I fix it?

![o_crop](https://github.com/user-attachments/assets/66b640af-da18-4d25-a76e-ade868c812b4)
![l_crop](https://github.com/user-attachments/assets/2e458653-174c-4737-8007-68587556bcaf)
![r_crop](https://github.com/user-attachments/assets/dd901a21-d1a3-4c53-b6e6-243c0696c1a1)
![all_crop](https://github.com/user-attachments/assets/777c313f-11e6-42e3-a508-469c5dbef807)

**Comment by geopavlakos** [comment]
Please check this issue: https://github.com/geopavlakos/hamer/issues/9#issuecomment-1865148920
