### ISSUE TITLE
Relative position between left and right hands

### ISSUE THREAD

**Issue by xungeer29** [geopavlakos/hamer#9]
Thanks for you great work!
The rendering result is very good, but why is the relative position between the hands so poor?
![image](https://github.com/geopavlakos/hamer/assets/32890569/96bc6f69-663d-4fa0-91ff-430b2f445ea3)
![image](https://github.com/geopavlakos/hamer/assets/32890569/7e91afca-9945-4f83-b689-244eb9228343)
![image](https://github.com/geopavlakos/hamer/assets/32890569/0ae62efc-ce0a-4ef9-bea6-f650d18e0026)

**Comment by geopavlakos** [comment]
Our HaMeR network estimates the hand pose from the local bounding box of the hand. The translation is inferred as a function of the provided focal length. The demo uses a large focal length that approximates weak perspective projection. If you use a more reasonable focal length value (e.g., f=1000), you will get something that looks like this:

<img width="605" alt="Screenshot 2023-12-20 at 12 43 41 PM" src="https://github.com/geopavlakos/hamer/assets/1571144/d7d93b9e-9cc7-4b3e-bb78-b265932cf316">

<img width="767" alt="Screenshot 2023-12-20 at 12 43 51 PM" src="https://github.com/geopavlakos/hamer/assets/1571144/bcd154ba-1eb1-4895-a1f5-96dd4c784a5f">

Please check also the explanation in [this issue](https://github.com/shubham-goel/4D-Humans/issues/16).
