### ISSUE TITLE
Rotation Axis for Hand_Pose

### ISSUE THREAD

**Issue by edessa** [geopavlakos/hamer#91]
Hello,

I am trying to understand the axis convention for the hand_pose prediction under pred_mano_params. This variable is meant to be a 3x3 rotation matrix wrist pose in the frame of reference of the camera. So, in a rotation matrix the first column indicates the direction of the x-axis, the second column the direction of the y-axis, and the third column the direction of the z-axis. How do each of these axis map onto the hand? For example, does the x-axis and y-axis lie on the plane of the wrist, and the z-axis points out of the wrist? I cannot find any information for this in this repository or anywhere else.

**Comment by geopavlakos** [comment]
Unfortunately, this is not documented somewhere. You might want to visualize the predictions to get the intuition for that.
