### ISSUE TITLE
how to calculate the distance between Index finger and thumb

### ISSUE THREAD

**Issue by yanrihong** [geopavlakos/hamer#95]
I want to measure the distance relative distance Index finger and thumb，
how could i deal with the hamer output?
thanks for your reply!

**Comment by yanrihong** [comment]
actually, I dont konw what number of finger is relatived to the index finger and thumb finger

**Comment by yanrihong** [comment]
problem solved！

**Comment by PannagaS** [comment]
@yanrihong how did you solve this problem??
